import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { getAllResearch, getResearch, type ResearchFrontmatter } from "@/lib/content";
import { getPaper, getPaperSlugs } from "@/lib/paper";
import PaperHeader from "@/components/paper/PaperHeader";
import PaperTOC from "@/components/paper/PaperTOC";
import { withBase } from "@/lib/paths";

export function generateStaticParams() {
  return getPaperSlugs().map((slug) => ({ slug }));
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ slug: string }>;
}): Promise<Metadata> {
  const { slug } = await params;
  const paper = getPaper(slug);
  if (!paper) return {};
  const doc = getResearch(slug);
  const fm = doc?.frontmatter as ResearchFrontmatter | undefined;
  const canonical = `/research/${slug}/paper`;
  const SITE = "https://the-unlikely-lab.github.io/the-unlikely-lab";
  return {
    title: paper.manifest.title,
    description: `Full HTML article: ${paper.manifest.title} — The Unlikely Lab.`,
    authors: fm?.publication?.authors?.map((name) => ({ name })),
    alternates: { canonical },
    openGraph: {
      title: `${paper.manifest.title} | The Unlikely Lab`,
      description: fm?.description ?? "Full HTML article from The Unlikely Lab.",
      type: "article",
      url: canonical,
      authors: fm?.publication?.authors,
    },
    other: {
      "citation_title": paper.manifest.title,
      ...(fm?.publication?.doi
        ? {
            "citation_doi": fm.publication.doi,
            "citation_pdf_url": `${SITE}/research/${slug}/assets/paper.pdf`,
          }
        : {}),
    },
  };
}

export default async function PaperPage({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { slug } = await params;
  const paper = getPaper(slug);
  if (!paper) notFound();

  let codeUrl: string | undefined;
  let dataUrl: string | undefined;
  let publication: ResearchFrontmatter["publication"] | undefined;
  {
    const doc = getResearch(slug);
    if (doc) {
      const fm = doc.frontmatter as ResearchFrontmatter;
      codeUrl = fm.codeUrl;
      dataUrl = fm.dataUrl;
      publication = fm.publication;
    }
  }

  const pdfHref = withBase(`/research/${slug}/assets/paper.pdf`);

  return (
    <article lang="en" className="paper-article">
      <p className="mb-6 text-sm print:hidden">
        <Link href={`/research/${slug}`}>← Back to research overview</Link>
      </p>

      <PaperHeader manifest={paper.manifest} publication={publication} />

      {/* Paper controls — only links that actually exist */}
      <div className="mb-10 flex flex-wrap items-center gap-x-4 gap-y-2 border-y border-neutral-200 py-3 font-mono text-sm print:hidden">
        <span
          className="border-b-2 border-black pb-0.5 font-medium text-black"
          aria-current="true"
        >
          HTML
        </span>
        {paper.hasPdf && (
          <a href={pdfHref} className="no-underline text-neutral-700 hover:text-black">
            PDF
          </a>
        )}
        {codeUrl && (
          <a href={codeUrl} rel="noopener noreferrer" className="no-underline text-neutral-700 hover:text-black">
            Code
          </a>
        )}
        {dataUrl && (
          <a href={dataUrl} rel="noopener noreferrer" className="no-underline text-neutral-700 hover:text-black">
            Data
          </a>
        )}
      </div>

      <PaperTOC entries={paper.manifest.toc} />

      {/*
        Controlled build artifact: generated by scripts/paper/build.mjs from the
        real manuscript sources; sanitized (scripts/inline handlers stripped) at
        generation time. Not user-editable input.
      */}
      <div className="paper-body" dangerouslySetInnerHTML={{ __html: paper.html }} />
    </article>
  );
}
